{% set name = "immutabledict" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0341ee9cc84cb318fe06aa25c89d27e2564463924063d3f5e976fd0fa207849a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - poetry
  run:
    - python

test:
  imports:
    - immutabledict

about:
  home: https://github.com/corenting/immutabledict
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A fork of frozendict, an immutable wrapper around dictionaries.

extra:
  recipe-maintainers:
    - althonos
