{% set name = "immutabledict" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 673fb8f30f46d23dd394050b979f5b7f4c5398982b99ebc854fb873e646b967a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - poetry
  run:
    - python >=3.6

test:
  imports:
    - immutabledict

about:
  home: https://github.com/corenting/immutabledict
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A fork of frozendict, an immutable wrapper around dictionaries.

extra:
  recipe-maintainers:
    - althonos
